// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import HeaderComponent from "./components/HeaderComponent";
import FooterComponent from "../components/FooterComponent";
import HeaderComponent from "../components/HeaderComponent";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased w-full max-w-[1152px] mx-auto bg-[]`}
      >
        <HeaderComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}

